#creation of arrays

In [ ]:
#numpy---->1-d,2-d,3-d
import numpy as np
#1-d called as vector i.e 1d is combination of 0-d matrix
np.array([1,2,3,4,4])

array([1, 2, 3, 4, 4])

In [ ]:
#2d called as matrix i.e is combination of 1d matrix
np.array([[1,2,3],[4,5,8]])

array([[1, 2, 3],
       [4, 5, 8]])

In [ ]:
#3D called as tensor i.e 3d is combination of 2d matrix
a1=np.array([[[1,2,3],[2,3,1]],[[1,1,1,],[1,2,1]]])
print(a1)
print(type(a1))
np.ndim(a1)

[[[1 2 3]
  [2 3 1]]

 [[1 1 1]
  [1 2 1]]]
<class 'numpy.ndarray'>


3

In [ ]:
# prompt: what is numpy

print("""
NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices,
along with a large collection of high-level mathematical functions to operate on these arrays.
""")


In [ ]:
#dtype
a1=np.array([1,2,3],dtype=bool)
a2=np.array([1,2,1],dtype=complex)
a1,a2

(array([ True,  True,  True]), array([1.+0.j, 2.+0.j, 1.+0.j]))

In [ ]:
#np.arange(start,end,increment/decrement) last one excluded
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#reshape---> convert into ur required dimension
#product of rows nd columns is should equal to no. of elelments
np.arange(1,10,1).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#np.ones,np.zeroes----> neural n/w's
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#np.random
np.random.random((1,3))

array([[0.76965504, 0.52099187, 0.79453388]])

In [ ]:
#np.linspace--->(start,end,no. of items/how much should start and end divide)
np.linspace(1,10,5)
# ending is involved

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array atrributes

In [ ]:
#1d,2d,3d
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)


In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#ndim--> tells dimesnion of array
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [ ]:
#shape(2,2,2)--->3d(no. of 2d matrices,rows,col)
a1.shape,a2.shape,a3.shape


((10,), (3, 4), (2, 2, 2))

In [ ]:
#size---> no. of items
a3.size

8

In [ ]:
#item size---> no of bits it take
a3.itemsize

8

In [ ]:
a4=np.arange(12,dtype=np.int32)
a4.itemsize
# int32 takes 4 bites but dfault is int64 but in numpy you can change memory

4

In [ ]:
a5=np.arange(3,dtype=np.int8)
a5.itemsize

1

In [ ]:
#dtype----> gives memory occupation
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)
print(a4.dtype)
print(a5.dtype)
a1.dtype,a2.dtype,a3.dtype,a4.dtype,a5.dtype

int64
float64
int64
int32
int8


(dtype('int64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int32'),
 dtype('int8'))

# Changing datatype

In [ ]:
#astype----> remove access memory
a1.astype(np.int32)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#Array opertions

In [ ]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#arthemetic /scalar operations
1,a1+2,2,a2+12,3,a1-2,4,a1*10,5,a2**2,6,a1/2,7,a2%2

(1,
 array([[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]]),
 2,
 array([[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]),
 3,
 array([[-2, -1,  0,  1],
        [ 2,  3,  4,  5],
        [ 6,  7,  8,  9]]),
 4,
 array([[  0,  10,  20,  30],
        [ 40,  50,  60,  70],
        [ 80,  90, 100, 110]]),
 5,
 array([[144, 169, 196, 225],
        [256, 289, 324, 361],
        [400, 441, 484, 529]]),
 6,
 array([[0. , 0.5, 1. , 1.5],
        [2. , 2.5, 3. , 3.5],
        [4. , 4.5, 5. , 5.5]]),
 7,
 array([[0, 1, 0, 1],
        [0, 1, 0, 1],
        [0, 1, 0, 1]]))

In [ ]:
#relational---> gives true or false
1,a1>1,2,a2==12,3,a1<4,4,a1!=1


(1,
 array([[False, False,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]),
 2,
 array([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]]),
 3,
 array([[ True,  True,  True,  True],
        [False, False, False, False],
        [False, False, False, False]]),
 4,
 array([[ True, False,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]))

In [ ]:
#vector operations/arthemetic operations
1,a1+a2,2,a1-a2,3,a1/a2,4,a1&a2,5,a1|a2,6,a1**a2,7,a1^a2,8,a1%a2,9,a1==a2

(1,
 array([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]),
 2,
 array([[-12, -12, -12, -12],
        [-12, -12, -12, -12],
        [-12, -12, -12, -12]]),
 3,
 array([[0.        , 0.07692308, 0.14285714, 0.2       ],
        [0.25      , 0.29411765, 0.33333333, 0.36842105],
        [0.4       , 0.42857143, 0.45454545, 0.47826087]]),
 4,
 array([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]),
 5,
 array([[12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]]),
 6,
 array([[                   0,                    1,                16384,
                     14348907],
        [          4294967296,         762939453125,      101559956668416,
            11398895185373143],
        [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
          6839173302027254275]]),
 7,
 array([[12, 12, 12, 12],
        [20, 20, 20, 20],
        [28, 28, 28, 28]]),
 8,
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 

# Array functions


In [ ]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1
#round (matrix*where to round)--->rounds upto 100

array([[17., 62., 80.],
       [80., 83., 15.],
       [50., 78., 90.]])

In [ ]:
#max/min/sum/pro axis=0---->column,axis=1--->row
np.max(a1),np.max(a1,axis=0),np.max(a1,axis=1),np.sum(a1),np.sum(a1,axis=0),np.sum(a1,axis=1),np.prod(a1),np.prod(a1,axis=0),np.prod(a1,axis=1)

(np.float64(90.0),
 array([80., 83., 90.]),
 array([80., 83., 90.]),
 np.float64(555.0),
 array([147., 223., 185.]),
 array([159., 178., 218.]),
 np.float64(2947793472000000.0),
 array([ 68000., 401388., 108000.]),
 array([ 84320.,  99600., 351000.]))

In [ ]:
#mean/median/std/var
np.mean(a1),np.mean(a1,axis=0),np.mean(a1,axis=1),np.median(a1),np.median(a1,axis=0),np.median(a1,axis=1),np.std(a1),np.std(a1,axis=0),np.var(a1),np.var(a1,axis=0)


(np.float64(61.666666666666664),
 array([49.        , 74.33333333, 61.66666667]),
 array([53.        , 59.33333333, 72.66666667]),
 np.float64(78.0),
 array([50., 78., 80.]),
 array([62., 80., 78.]),
 np.float64(26.88659310676771),
 array([25.72936066,  8.9566859 , 33.24989557]),
 np.float64(722.8888888888889),
 array([ 662.        ,   80.22222222, 1105.55555556]))

In [ ]:
#dot product
a1=np.arange(1,10,1).reshape(3,3)
a2=np.arange(6).reshape(3,2)
np.dot(a1,a2)

array([[16, 22],
       [34, 49],
       [52, 76]])

In [ ]:
#log and exponents
np.log(a1),np.exp(a1)

(array([[0.        , 0.69314718, 1.09861229],
        [1.38629436, 1.60943791, 1.79175947],
        [1.94591015, 2.07944154, 2.19722458]]),
 array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
        [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]]))

In [ ]:
#round/floor/ceil
a1=np.random.random((2,3))*100
np.round(a1)
#round ---> round off to nearest integer

array([[ 1., 55., 93.],
       [49., 18., 72.]])

In [ ]:
#floor/ceil
np.floor(a1),np.ceil(a1)
#floor 6.1 output=6<-----
#ceil 6.1 output=7----->


(array([[ 1., 55., 93.],
        [48., 17., 72.]]),
 array([[ 2., 56., 94.],
        [49., 18., 73.]]))

# Indexing and slicing

In [ ]:
#1d,2d,3d
a1=np.arange(10)
a2=np.arange(9).reshape(3,3)
a3=np.arange(8).reshape(2,2,2)
1,a1,2,a2,3,a3

(1,
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 2,
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 3,
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

In [ ]:
#indexing for 1d array i.e
#0,1,2,3,.....--->+ve indexing
#........-3,-2,-1---> -ve indexing
print(a1[-1],a1[0],a1[2])

9 0 2


In [ ]:
#indexing in 2d    matrix[row,col]
#--->col  0,1,2
#!rows    1
#         2
a2[1,1],a2[0,0],a2[2,2],a2[2,1]

(np.int64(4), np.int64(0), np.int64(8), np.int64(7))

In [ ]:
#indexing in 3d   matrix[which 2d array want,row in 2d,col in 2d]
a3[0,0,1],a3[1,1,1],a3[0,0,0]
#indexing in 4d matrix[which 3d u want,which 2d u want,row,column]
#indexing in nd matrix[which nd u want,which n-1 d u want ......,when 2d comes,row,column]

(np.int64(1), np.int64(7), np.int64(0))

In [ ]:
#slicing in 1d----> last not included   mat[first,last,gap b/w first and last]--->+ve indexing   mat[last,first,jump]--->-ve indexing
a1,a1[2:5],a1[-3:-1],a1[1:3:2]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([2, 3, 4]),
 array([7, 8]),
 array([1]))

In [ ]:
#slicing in 2d   mat[row:,:col]---. if u want to include all rows or col make sure ":" has to present
a2,a2[0,:]

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([0, 1, 2]))

In [ ]:
#steps:
# make u question which row u want and which col u want thats it matrix[startingrow:endingrow,startingcol:ending col]  ::---> 2 times jump >::: 3 times jump
a2[:,2],a2[2,:],a2[0:2,1:3],a2[:,0:2],5,a2[:,:],a2[0:3:2,:],a2[0:3:2,0:3:2],a2[2:3,2:3],a2[0,0:2],a2[::2,::2]

(array([2, 5, 8]),
 array([6, 7, 8]),
 array([[1, 2],
        [4, 5]]),
 array([[0, 1],
        [3, 4],
        [6, 7]]),
 5,
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[0, 1, 2],
        [6, 7, 8]]),
 array([[0, 2],
        [6, 8]]),
 array([[8]]),
 array([0, 1]),
 array([[0, 2],
        [6, 8]]))

In [ ]:
#slicing in 3d mat[which 2d mat u want ,]
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[2,:,:],a3[0,:,:],a3[1,0:2,0:2],a3[1,::2,::2],a3[1,0:3:2,0:3:2],a3[0,:,1:3],a3[1],a3[::2],a3[0:3:2]

(array([[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[ 9, 10],
        [12, 13]]),
 array([[ 9, 11],
        [15, 17]]),
 array([[ 9, 11],
        [15, 17]]),
 array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]),
 array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],
 
        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]]),
 array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],
 
        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]]))

In [ ]:
a3[2,::2,:2],a3[1,:,1],a3[2,1:,1:]

(array([[18, 19],
        [24, 25]]),
 array([10, 13, 16]),
 array([[22, 23],
        [25, 26]]))

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [ ]:
#1d
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
#2d---> iterating on 2d prints 1d arrays
for i in a2:
  print(i)

[0 1 2]
[3 4 5]
[6 7 8]


In [ ]:
#3d--> iterting in 3d prints 2d arrays
for i in a3:
  print(i)
  #or use  loops to iterate over 1d,2d,3d
  # for j in i:
  #   print(j)
  #   for k in j:
  #     print(k)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [ ]:
#nditer---> iterter through elements
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# reshaping

In [ ]:
#reshape--> converts one shape to another
a3.reshape(3,9)
a3.reshape(3,3,3)
a3.size
a3.itemsize
a3.shape

(3, 3, 3)

In [ ]:
#Transpose---> a2.T gives transpose shortcut
a2,np.transpose(a2),a2.T

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]]),
 array([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]]))

In [ ]:
#ravel---. converts into 1d array
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

## **stacking**

In [ ]:
#horizontal stacking----> 1+1=11----> insert matrices one after another
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a4,a5,np.hstack((a4,a5))
#(3,4)+(3,4)==(3,8)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[ 0,  1,  2,  3, 12, 13, 14, 15],
        [ 4,  5,  6,  7, 16, 17, 18, 19],
        [ 8,  9, 10, 11, 20, 21, 22, 23]]))

In [ ]:
#vertical stacking---->shape should be same (3,4)+(3,4)==(6,4)
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitiing

In [ ]:
#horizontal splitiing---> revrse of stacking--. splits matrices rows and columns
a4,np.hsplit(a4,2),np.vsplit(a4,3)


(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 [array([[0, 1],
         [4, 5],
         [8, 9]]),
  array([[ 2,  3],
         [ 6,  7],
         [10, 11]])],
 [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])])